### ISSUE TITLE
project closed?

### ISSUE THREAD

**Issue by warioishere** [AE9999/matrix-lightning-tip-bot#2]
Hi @AE9999  just writing in the hope to get an answer maybe?

Ist this project closed? We would like to give this a push, since matrix and lightning is evolving and continuing to grow, and what matrix misses, is a lightning implementation that is kept up to date and maintained. I think your project will have a huge interest, if it would be taken up again!

Hope I get a reply from you guys!

**Comment by AE9999** [comment]
Hi @warioishere it's there is interest. I'll in the future soon if I can get this up to dat again and work & create a running demo site again.

**Comment by warioishere** [comment]
> Hi @warioishere it's there is interest. I'll in the future soon if I can get this up to dat again and work & create a running demo site again.

awesome if you could pick up the project again. We could also help in testing, because we also have our own lnbits instance. I am not a coder and unfurtunatly not a developer, so I am not sure, if its save to try it out at the current state because lots of things have changed matrixwise and also lnbits wise since 3 years.

greetings, will be follwing this with very high interesst, and I think others gonna pick this up too as soon as some maintainance and updates are seen.

**Comment by AE9999** [comment]
Will take a look this Sunday. Will keep you up to date.

**Comment by AE9999** [comment]
I updated rust and all libraries to their latest version, got every thing to compile again. Will need to test on my own version of matrix again, which I'll do next week. Should have a working version again by next Saturday. Any progress can be tracked in this branch:

https://github.com/AE9999/matrix-lightning-tip-bot/tree/feature/update-to-latest-version

**Comment by warioishere** [comment]
> I updated rust and all libraries to their latest version, got every thing to compile again. Will need to test on my own version of matrix again, which I'll do next week. Should have a working version again by next Saturday. Any progress can be tracked in this branch:
> 
> https://github.com/AE9999/matrix-lightning-tip-bot/tree/feature/update-to-latest-version

That's really awesome man, following this with huge interest. Let me know when I can test this on our server too! That's what has been missing on matrix. Lots of btc groups leaving tg because of recent actions.

**Comment by AE9999** [comment]
Hi @warioishere I've merged the updated code into master and I've relaunched & tested the bot over at https://element.s-software-solutions.nl/#/room/#matrix-lightning-tip-bot-discussion:s-software-solutions.nl. Feel free to experiment with it at your leisure. If you have questions you can contact me here or contact me at the matrix instance.

**Comment by AE9999** [comment]
Closed as every updates have been completed

**Comment by warioishere** [comment]
Thanks pal, Ill check by on your server as soon as possible, I got a shit load to do. Running arround all day even on weekends


> Hi @warioishere I've merged the updated code into master and I've relaunched & tested the bot over at https://element.s-software-solutions.nl/#/room/#matrix-lightning-tip-bot-discussion:s-software-solutions.nl. Feel free to experiment with it at your leisure. If you have questions you can contact me here or contact me at the matrix instance.

**Comment by warioishere** [comment]
I cannot enter your matrix room #matrix-lightning-tip-bot-discussion:s-software-solutions.nl
Is it private? Getting an error.

**Comment by AE9999** [comment]
Hmm no room is not private and should be public with this link.

https://matrix.to/#/#matrix-lightning-tip-bot-discussion:s-software-solutions.nl

Will take a look later.

**Comment by AE9999** [comment]
Hmm @warioishere looks like matrix room listing / publicity settings have changed since I used the ansible playbook 3 years ago. Will double check this weekend. Should have an update by next week.

**Comment by warioishere** [comment]
> Hmm @warioishere looks like matrix room listing / publicity settings have changed since I used the ansible playbook 3 years ago. Will double check this weekend. Should have an update by next week.

no stress, let me know when i can come by

**Comment by warioishere** [comment]
@AE9999 

I would also try this on my matrix server, but the problem is, creating bots, is not so easy for me.. maybe you could also create a repo with a bot that can be implemented? Or maybe the solution/code/tutorial on how you create that bot? As far as I understood, the solution you have is just the backend, right

**Comment by AE9999** [comment]
No the code is the entire thing. I finally finished reinstalling my matrix server. Join:

https://matrix.to/#/#matrix-lightning-tip-bot-discussion:s-software-solutions.nl

To check. Once you are there you can use !help to see the commands. If I am there I'll send you some sats which you can reroute to your own prefered lightning source

**Comment by AE9999** [comment]
> @AE9999
> 
> I would also try this on my matrix server, but the problem is, creating bots, is not so easy for me.. maybe you could also create a repo with a bot that can be implemented? Or maybe the solution/code/tutorial on how you create that bot? As far as I understood, the solution you have is just the backend, right

The bot part can be found here:

https://github.com/AE9999/matrix-lightning-tip-bot/blob/master/src/matrix_bot/mod.rs

It is basically an amalgamation of  the examples listed in the matrix rust sdk https://github.com/matrix-org/matrix-rust-sdk/tree/main/examples

Rust is a however a bit of a niche programming langue, but there are plenty of options https://matrix.org/ecosystem/sdks/

The bitcoin / lightning backend is simply a lnbits instance I am running through tor.

**Comment by warioishere** [comment]
can be closed, working fine so far, tested on own lnbits instance.
Thanks to AE9999!
